lifeomic/one-schema

- src/generate-axios-client.test.ts
- src/generate-axios-client.ts
- src/integration.axios.test.ts
- src/test-utils.ts
This encoding behavior is wrong for query params. It's double-encoding the input. Two commits:
1. Migrate `integration.axios.test` to use an actual HTTP server to validate the requests from the generated client, rather than just asserting on Axios parameters.
2. Correct the bad behavior.
> fix: correct encoding behavior

- .github/workflows/release.yml
- package.json
Making this package publish publicly, after discussion [here](https://lifeomic.slack.com/archives/C0137E2L8C9/p1654796924703889).
The repo is already publicly visible -- this just makes the NPM package public too.
> fix: make package public

- src/json-schema.ts
- src/meta-schema.test.ts
- src/meta-schema.ts
Currently, you can side-step the standard schema validations by using a `$ref` for your request schema.
This fixes that!
> fix: resolve refs in request schemas when validating

- README.md
@xdumaine asked about specific docs for adopting `one-schema` in an existing service.
This PR doesn't add those docs, but it does dramatically improve the detail around "how to write the schema", which should at least help.
> fix: improve docs about schema definition

- README.md
the use of Post as a noun is confusing with Post being a REST verb
I changed `message` to `label` just because `item.message` seemed a bit non-intuitive of an example.
> use Item and label instead of Post and message in example

- src/koa.test.ts
- src/koa.ts
I have continued to encounter issues with the global `declare` that this project has been using to allow correct typing of the `request.body` property.
I discovered a much cleaner solution. See the in-line comments.
> fix: make body typing more deterministic

- README.md
- package.json
- src/integration.koa.test.ts
- src/koa.test.ts
- src/koa.ts
- yarn.lock
This typing thing seems to be a continuous moving target. Here's what happened:
- I updated a service to use the latest change from #43. It worked to type the `request.body` field more deterministically. Nice!
- But, it _removed_ every other field from the context. So, the context just looked like: `{ request: { params: {...}, body: {...} }`. WTF?
For whatever reason, using `@koa/router` instead of `koa-router` causes this to happen. In particular, the behavior of `Omit<ParameterizedContext>` changes drastically:
```typescript
import { ParameterizedContext } from 'koa';
// When koa-router is installed:
type Modified = Omit<ParameterizedContext, 'request'>
// > Full context minus `request` ✅
// When @koa/router is installed:
type Modified = Omit<ParameterizedContext, 'request'>
// > { [x: …
```
> feat: test against @koa/router and clean up typing

- src/integration.koa.test.ts
- src/koa.test.ts
- src/koa.ts
This change should result in much more deterministic inferences of the `State` and `Context` of the passed router.
**tl;dr**
_Before_, TypeScript attempted to determine the `State` + `Context` types by deciding between the passed `Router` and the passed `implementation. This could result in inconsistent behavior, and sometimes needing to explicitly override the types:
```typescript
type State = { customState: string };
const router = new Router<State>();
// sometimes, have to explicitly set these generics. super lame, since now we're
// making it explicit in two places (here, and just above on the Router) 😢
implementSchema<typeof Schema, State, {}>(..., {
on: router,
implementation: {
'GET /whatever': (ctx) => {
ctx.customState;
}
}
})
```
_Now_, the `State` and `Context` types are …
> feat!: use `infer` statements to better infer router state + context

- README.md
- src/generate-axios-client.test.ts
- src/generate-axios-client.ts
- src/meta-schema.ts
- src/openapi.test.ts
- src/openapi.ts
- src/types.ts
Adding a `Description` field to endpoints provides a few cool benefits.
A developer can document an endpoint's behavior _once_ in the service, and have the description rendered directly into JSDoc for all consumers using the generated Axios client.
I also updated the OpenAPI spec generation to handle the field. This takes us further towards a more complete documentation generation flow.
> feat: support a Description field on endpoints

- src/bin/cli.ts
- src/openapi.test.ts
- src/openapi.ts
Two:
- Generate OpenAPI v3.0.0 specs instead of v3.1.0. Our current API reference site uses v3.0.0, so this ensures that we don't accidentally use any v3.1.0 features.
- Fix an OpenAPI spec generation bug. Called out below.
> fix: generate OpenAPI v3.0.0 specs

- src/openapi.test.ts
- src/openapi.ts
I accidentally put the `Description` in the wrong place in #46.
> fix: set endpoint description in correct place in OpenAPI spec

- .gitignore
- src/bin/cli.test.ts
- src/bin/cli.ts
See the in-line comment re: YAML "line folding".
To confirm the change is doing what we want, you can look at the failing test output on the first commit of this PR.
> fix: stop adding newlines to yaml output

- package.json
- src/__snapshots__/router.test.ts.snap
- src/index.ts
- src/router.test.ts
- src/router.ts
- yarn.lock
**Overview**
Currently, a developer build a full-stack `one-schema`-powered application has to go through many steps to get the typing benefits across their stack. Roughly:
- In service repo, write the YAML schema for API schema in their service repo.
- In service repo, run `one-schema generate-api-types ...` to generate types for the server-side code.
- Wait for new service code to deploy.
- In client repo, run `one-schema fetch-remote-schema ...` to introspect the updated schema.
- In client repo, run `one-schema generate-axios-client ...` to generate an updated client.
This PR is focused exclusively on the first two steps:
> - In service repo, write the YAML schema for API schema in their service repo.
> - In service repo, run `one-schema generate-api-types ...` to generate types for …
> feat: introduce OneSchemaRouter as a simpler approach

- README.md
- docs/yaml-flow.md
This is essentially a "refactor" of the docs, in response to #52. At a high level, my goals were:
- add basic documentation for using the new `OneSchemaRouter`
- "deprecate" docs for the old YAML-based flow, by moving them out of the README.
- Re-organize usage guide to be focused on "getting someone up and running quickly".
> docs: update docs for OneSchemaRouter

- .github/lifeomic-probot.yml
This is the preferred reporting channel for open source packages.
> fix: use open-source channel to report failures

- package.json
- src/router.test.ts
- src/router.ts
- yarn.lock
Adding a method for returning a well-typed client for a router. I think this will be helpful for quickly writing unit tests in a service.
```typescript
const router = OneSchemaRouter.create({
using: new Router(),
introspection: undefined,
})
.declare({
route: 'GET /items/:id',
name: 'getItemById',
request: z.object({ filter: z.string() }),
response: z.object({ id: z.string() }),
});
const client = router.client({ /* axios instance */ })
await client.getItemById(...)
```
> feat: add a method for immediately getting a client for the router

- src/router.test.ts
- src/router.ts
Today, `OneSchemaRouter` only provides runtime enforcement of _request_ schemas. It does _not_ validate the shape of response objects, instead relying only on type inference to enforce the correct shape.
This is effective only to a degree. It still allows for at least a few bad patterns:
- response values can have the same primitive type (and thus pass type validation), but not match the schema (e.g. you could return `'bogus'` for a `z.string().datetime()` value.
- response values can be a _superset_ of the required response type, thus allowing unintended extra fields to be returned via the API -- e.g. for a schema `{ id: z.string(); }`, a value like `{ id: string; someOtherField: number` can be returned in the API implementation _without_ causing type errors.
I'd like to propose …
> feat!: enforce response conforms to schema

- src/koa-utils.ts
- src/router.test.ts
- src/router.ts
This PR adds first-class support for using Zod effects on request schemas. A simple motivating use case:
Most LifeOmic APIs that support paging use a common query parameter called `pageSize`. Consider this implementation function:
```typescript
const impl: (ctx) => {
// This is a string, because Koa automatically deserializes query parameters as strings.
ctx.request.query.pageSize;
}
```
By allowing our custom handlers to _replace_ the `ctx.request.query` properties, we can allow transforms when parsing. e.g.
```typescript
const request = z.object({
// This coercion can now actually be applied at runtime
pageSize: z.coerce.number();
})
const impl: (ctx) => {
ctx.request.query.pageSize; // number
// Previously, ^this would be typed as a `number`, but would actually be a `string` at runtime …
```
> feat!: support modifications during parsing of inputs

- src/openapi.test.ts
- src/openapi.ts
looks like `type: integer` or `type: number` is not supported yet when generating openapi spec
this blocks https://github.com/lifeomic/patient-ml-service/pull/174
> fix(PML-222): unexpected type in generated openapi spec

- src/openapi.test.ts
- src/openapi.ts
See this thread from #73 for more context: https://github.com/lifeomic/one-schema/pull/73#discussion_r1261593666.
As evidenced by the modified test, this change expands on #73 to add generalized support for arbitrarily complicated query parameter schemas.
> fix: further improve OpenAPI query schema support

- src/introspection.ts
- src/koa.ts
- src/router.test.ts
- src/router.ts
- src/types.ts
You can now optionally configure an OpenAPI introspection endpoint for your `one-schema` service. Specifically, you can add an `openapi` field to your `introspection` config in this way:
```typescript
OneSchemaRouter.create({
using: new Router(),
introspection: {
route: "/private/introspection",
serviceVersion: "123",
openApi: {
route: "/private/openapi",
info: {
title: "My Service",
},
},
},
});
```
The above code will allow a consumer to fetch the OpenAPI schema for this service by calling the `/private/openapi` route. The `info` block is the OpenAPI [schema metadata](https://swagger.io/specification/#info-object) for the service.
> feat: optional openapi schema introspection

- src/generate-api-types.test.ts
- src/generate-axios-client.test.ts
- src/generate-endpoints.ts
A small enhancement: for the `schema.yaml` flow, this PR makes a change to pass a route's description into the rendered ts code for the `Endpoints` type. Since you refer to `one-schema` routes by their route, its especially useful to have the route description propagate down into the `Endpoints` type, e.g. so you can see a route's description on hover:
https://github.com/lifeomic/one-schema/assets/21148260/7d04e64c-9bab-4c49-8c50-c32409341812
> fix: include route description as ts comment

- src/koa-utils.ts
- src/koa.ts
- src/router.test.ts
- src/router.ts
Many existing LifeOmic services use the "variadic middleware" style when declaring routes:
```typescript
router.get(
'/something',
middleware1,
middleware2,
middleware3,
actualImplementation
);
```
Currently, it's very diffuclt to adopt `one-schema` in a service that uses this^ pattern, since it can't be represented in a `OneSchemaRouter` without significant refactoring.
That changes today! This PR introduces support for this syntax in a non-breaking way, thanks to TypeScript magic:
```typescript
router
// This is the preferred path, supported today. Single implementation function. This is preferred + clearer!
.implement(
'POST /items',
async (ctx) => {
return item;
}
)
// But now, this also works:
.implement(
'POST /items',
async (ctx, next) => {
await doSomethingElse();
await next();
}, …
```
> feat: support variadic middleware for routes

- src/koa-utils.ts
- src/koa.ts
- src/router.test.ts
- src/router.ts
This PR rolls back the changes from #85.
We discovered that #85 significantly degraded the behavior of auto-complete in route implementations. This is super lame and antithetical to the value of `one-schema`. Since there has been minimal/no adoption of this new feature, going to roll it back as a `fix:` for now, until we can find a way to release it without degrading auto-complete.
> Revert "feat: support variadic middleware for routes"

- package.json
Prettier is used in the CLI here: https://github.com/lifeomic/one-schema/blob/master/src/bin/cli.ts#L34
By not making this a production dependency, we force consumers to have `prettier` installed, and we use their version instead. This creates a bug for any consumers using `prettier` v3, which returns a `Promise` from `format`, instead of a synchronous `string`.
> fix: make prettier a production dependency

- src/__snapshots__/router.test.ts.snap
- src/bin/cli.ts
- src/generate-axios-client.test.ts
- src/generate-axios-client.ts
- src/integration.axios.test.ts
- src/router.test.ts
_INCLUDES BREAKING CHANGE_
In order to make integration in downstream consumers easier, we've migrated from generating separate code (`.js`) and declaration (`.d.ts`) files to only generating a single TypeScript (`.ts`) file. The main reason for this is that `tsc` does not include `.d.ts` files by default in its build process, which break consumers that have used this package before the build step, since they'll lose the generated `.d.ts` file when their build process generates its own from the `.js` file that this package also generates.
> feat: generate just typescript
